Creación de componente información de autor
christopherigm/lemon-web-app pull request #3
Opened 2021-07-14 04:31 UTC by GMR027

2021-07-15 16:16 UTC, christopherigm commented on src/modules/post-author-info/post-autor-info.tsx
> +const PostAuthorInfo = (props: any): React.ReactElement => {
Este componente muestra el titulo de la noticia, categoria fecha de creacion e informacion del autor.

Deberiamos renombrarlo con algo como HeaderPost

Ya que es el encabezado de la noticia y no solo informacion del autor

2021-07-15 16:16 UTC, christopherigm commented on src/modules/post-author-info/post-autor-info.tsx
> +    <div className='PostAuthor container row'>
Igual hay que renombrar las clases CSS a HeaderPost

2021-07-15 16:16 UTC, christopherigm commented on src/modules/post-author-info/post-autor-info.tsx
> +import 'src/modules/post-author-info/post-autor-info.scss';
Renombrar todos los archivos de este componente a header-post, incluyendo la carpeta del componente

2021-07-15 16:16 UTC, christopherigm commented on src/modules/post-author-info/post-autor-info.tsx
> +            <div className='PostAuthor__titleMayor col s12'>{props.title}</div>
Aqui hay que usar el componente de titulo, luego lo modificamos para pasarle un props para el tamano

2021-07-15 16:16 UTC, christopherigm commented on src/modules/post-content/post-content.scss
> +}
Falta agregar un espacio abajo de esta llave

2021-07-15 16:16 UTC, christopherigm commented on src/pages/post-detail/post-detail.tsx
>      author: {
En esta seccion es donde hay que agregar la foto y biografia del autor:

```
author: {
     data: {
          attributes: {
               first_name: '',
               last_name: '',
               img_picture: '',
               biography: ''
          }
     }
}
```

2021-07-15 16:16 UTC, christopherigm commented on src/pages/post-detail/post-detail.tsx
> +          author={post.relationships.author.data.attributes.first_name}
Y a parte hay que agregar el `last_name`, debemos mostrar el nombre y el apellido del autor.

2021-07-15 16:16 UTC, christopherigm commented on src/pages/post-detail/post-detail.tsx
> +          author={post.relationships.author.data.attributes.first_name}
Igual aca, cambiar `author` por `author_name`.

2021-07-15 16:16 UTC, christopherigm commented on src/pages/post-detail/post-detail.tsx
> +          UserProfile='temp'
Este props no es necesario, ya que vas a pasar cada uno de los campos requeridos. Also como:

- author_name=`${....ributes.first_name} ${...tributes.last_name}`
- picture=`{post.relationships.author.data.attributes.img_picture}`
- biography=`{post.relationships.author.data.attributes.biography}`

2021-07-15 16:16 UTC, christopherigm commented on src/modules/post-header-picture/post-header-picture.scss
> +}
Aqui esta al reves, primero deberiamos mostrar los 200px para movil y en escritorio cambiar el alto a 500px

Ejemplo:

```
.parallax {
    height: 200px; // Este es el alto en movil
}

@media screen and (min-with: 425px) { // Checa como estoy usando MIN en vez de MAX with
    .parallax {
        height: 500px; // Este es el alto en escritorio
    }
}
```

2021-07-15 17:58 UTC, christopherigm commented on src/modules/post-author-info/post-autor-info.tsx
> +          <div className='PostAuthor__date col s9 m10 l10'>{props.date}</div>
Hay que crear una funcion para regresar la fecha en un "formato legible". Aqui te dejo un ejemplo de como "parsear" la fecha que viene del API y mostrarla en forma clara:

![image](https://user-images.githubusercontent.com/35640157/125835005-6939309a-46d7-4dba-a0fb-0594efbf4af4.png)

Este es el codigo que debes meter en una function. La funcion debe regresar la fecha y la hora.

Tal vez puedes crear 2 funciones, una que regrese la hora en un buen formato y otra funcion que regrese la fecha en un buen formato.

Ejemplo de codigo:

```
const date = '2021-07-14T04:24:44.500945Z';
const parsedDate = new Date(date);
const months = [
  'Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio',
  'Agosto','Septiembre','Octubre','Noviembre','Diciembre'
];

const month = months[parsedDate.getMonth()];
const day = parsedDate.getUTCDate();
const year = parsedDate.getFullYear();
const hour = parsedDate.getHours();
const minutes = parsedDate.getMinutes();

console.log('Fecha:', `${month} ${day}, ${year}`);
console.log('Hora:', `${hour}:${minutes} hrs`)
```

2021-07-15 23:51 UTC, GMR027 commented on src/pages/post-detail/post-detail.tsx
> +          UserProfile='temp'
Listo, lo agregue de forma temporal

2021-07-16 00:10 UTC, GMR027 commented on src/pages/post-detail/post-detail.tsx
> +          author={post.relationships.author.data.attributes.first_name}
listo

2021-07-16 00:10 UTC, GMR027 commented on src/pages/post-detail/example.tsx
> +import React from 'react';
listo

2021-07-16 00:14 UTC, GMR027 commented on src/modules/post-author-info/post-autor-info.tsx
> +const PostAuthorInfo = (props: any): React.ReactElement => {
listo

2021-07-16 00:15 UTC, GMR027 commented on src/modules/post-author-info/post-autor-info.tsx
> +    <div className='PostAuthor container row'>
listo

2021-07-16 00:15 UTC, GMR027 commented on src/modules/post-content/post-content.scss
> +}
listo

2021-07-16 00:24 UTC, GMR027 commented on src/pages/post-detail/post-detail.tsx
>      author: {
listo pero no quedo

2021-07-16 00:25 UTC, GMR027 commented on src/pages/post-detail/post-detail.tsx
> +          author={post.relationships.author.data.attributes.first_name}
listo

2021-07-16 00:30 UTC, GMR027 commented on src/modules/post-header-picture/post-header-picture.scss
> +}
listo

2021-07-16 17:00 UTC, christopherigm requested changes

2021-07-16 17:00 UTC, christopherigm commented on src/pages/post-detail/post-detail.tsx
> +        <HorizontalSpace size='large' />
Cambiar el size a `medium`

2021-07-16 17:13 UTC, GMR027 commented on src/modules/header-post/header-post.scss
> +  }
listo

2021-07-16 17:14 UTC, GMR027 commented on src/modules/header-post/header-post.scss
> +}
listo

2021-07-16 17:14 UTC, GMR027 commented on src/modules/header-post/header-post.tsx
> +import { DateParser, HourParser } from 'src/modules/utils/date-parser';
listo

2021-07-16 17:16 UTC, GMR027 commented on src/modules/header-post/header-post.tsx
> +          <div className='PostAuthor__date col s9 m10 l10'>{`${date} - ${time}`}</div>
listo

2021-07-16 17:20 UTC, GMR027 commented on src/modules/header-post/header-post.tsx
> +        </div>
listo

2021-07-16 17:20 UTC, GMR027 commented on src/modules/post-author-biography/post-author-biography.scss
> +  &__image img {
listo

2021-07-16 17:21 UTC, GMR027 commented on src/modules/post-author-biography/post-author-biography.scss
> +}
listo

2021-07-16 17:22 UTC, GMR027 commented on src/modules/post-author-biography/post-author-biography.tsx
> +      <div className='PostBiography__info col s12 m10 l10'>
listo

2021-07-16 17:24 UTC, GMR027 commented on src/modules/post-content/post-content.tsx
> +        className='PostContent__content col s12 m10 l10 white-text'
listo

2021-07-16 17:24 UTC, GMR027 commented on src/modules/post-content/post-content.tsx
> +      <div className='PostContent__colum col m1 l1 hide-on-small-only'></div>
listo

2021-07-16 17:29 UTC, GMR027 commented on src/modules/post-header-picture/post-header-picture.scss
> +    height: 500px;
listo tiene 32 en movil y 65 en pc

2021-07-16 17:32 UTC, GMR027 commented on src/modules/utils/date-parser.ts
> +  console.log('Hora:', `${hour}:${minutes} hrs`);
listo

2021-07-16 17:33 UTC, GMR027 commented on src/pages/post-detail/post-detail.tsx
> +        <HorizontalSpace size='large' />
listo

2021-07-16 18:11 UTC, GMR027 commented on src/pages/post-detail/post-detail.tsx
> +          UserProfile='temp'
listo

2021-07-16 18:12 UTC, GMR027 commented on src/modules/post-author-info/post-autor-info.tsx
> +          <div className='PostAuthor__date col s9 m10 l10'>{props.date}</div>
listo

2021-07-16 18:29 UTC, GMR027 commented on src/modules/header-post/header-post.scss
> +  &__nameAuthor {
listo

2021-07-16 18:30 UTC, GMR027 commented on src/modules/utils/date-parser.ts
> +  console.log('Hora:', `${hour}:${minutes} hrs`);
listo

2021-07-16 20:27 UTC, christopherigm requested changes

2021-07-16 20:27 UTC, christopherigm commented on src/modules/header-post/header-post.tsx
> +        <div className='PostAuthor  col s12 m10 l10'>
Remover clase PostAuthor que ya esta definida en la linea 15

2021-07-16 20:29 UTC, christopherigm requested changes

2021-07-16 20:29 UTC, christopherigm commented on src/modules/header-post/header-post.tsx
> +        <div className='PostAuthor  col s12 m10 l10'>
Por que hay una col dentro de otra col?

2021-07-16 20:31 UTC, GMR027 commented on src/modules/header-post/header-post.tsx
> +        <div className='PostAuthor  col s12 m10 l10'>
ok retirado

2021-07-16 20:35 UTC, GMR027 commented on src/modules/header-post/header-post.tsx
> +        <div className='PostAuthor  col s12 m10 l10'>
revisado

2021-07-16 21:05 UTC, christopherigm approved these changes

2021-07-16 21:05 UTC, merged